version: '2'

services:
  php:
    image: yiisoftware/yii2-php:7.4-apache
    container_name: php-app
    ports:
      - '8000:80'
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - .:/app:delegated
    environment:
      - MYSQL_HOST=mysql-app
      - MYSQL_DATABASE=yii2db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: mysql-app
    ports:
      - '3306:3306'
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=yii2db

volumes:
  mysql-data:
